version: '3.8'

x-environment: &default-environment
  PREFECT_API_URL: "http://127.0.0.1:4200/api"
  PREFECT_UI_URL: "http://127.0.0.1:4200/api"
  PREFECT_SERVER_API_HOST: "0.0.0.0"

services:
  prefect:
    image: prefecthq/prefect:2-python3.11
    restart: always
    ports:
      - "4200:4200"
    environment:
      <<: *default-environment
    command: prefect server start
    networks:
      - backend-server

  prefect-worker:
    build: .
    environment:
      <<: *default-environment
      PREFECT_API_URL: "http://prefect:4200/api"  # Override for worker to use service name
    networks:
      - backend-server

networks:
  backend-server:
